### ISSUE TITLE
💙 Really nice tool

### ISSUE THREAD

**Issue by stritti** [heiko95/InsertCreator#26]
I will use an HW encoder (small congregation), but will share it with the others of my district.

I created a tool to support bothers & sisters to find the streams more easily. Maybe it is useful for you too: https://nak-sued.stream/

**Comment by heiko95** [comment]
Thank you for the info. 
We use a subdomain of a private domain for our community. This subdomain is redirected to the current YouTube link via a temporary redirect (HTTP 302). This meant that we only had to communicate a link once.
