### ISSUE TITLE
Background Transparency, insert size, Font color of the lower third Inserts, size of custom inserts

### ISSUE THREAD

**Issue by kaiwo77** [heiko95/InsertCreator#40]
Dear @heiko95 , 
- **Is it possible to adjust the trancparency of the created inserts?** 
The Insert "Bibelwort" has about 50-80% background transparency. 
Maybe there's an option to programm a custom adjustable background transparency? 

- **Can the size of the lower third inserts be adjusted in width and heigth?**
In combination with font size some inserts may be better with less size... just an idea

- **changing Font color**
If Background tranyparency is adjustable, the font color maybe has to be changed to f.e. white (if transparency is 100%)

- **Any chance to get the type of "Bibelwort" insert (on the whole screen) for custom inserts?**
There are dates and things to communicate sometimes where the custom inserts are difficult to handle (1st row **bold**, second row not, no chance to adjust these settings). 
A pretty nice option would be to create custom inserts like the "Bibelwort" insert. 1st custom "input box" is the headline and automatically **bold**, 2nd box is for free and custom inserts on the whole screen, maybe easier with up to 10 rows (2nd - 10th same formatting, the total of used boxes are displayed centered... 

Thanks in advance for feedback ;-)
Kai

**Comment by heiko95** [comment]
_Is it possible to adjust the trancparency of the created inserts?_
Yes: You can change the field "Transparenz Einblendefeld" in the [InsertSettings](https://github.com/heiko95/InsertCreator/wiki/10.-Anpassen-der-Einblenden) between 0 and 255.

_Can the size of the lower third inserts be adjusted in width and heigth?_
Yes: You can change the font Settings and the Position and Size Settings in the [InsertSettings](https://github.com/heiko95/InsertCreator/wiki/10.-Anpassen-der-Einblenden) between 0 and 255.

_changing Font color_
New issue created. See [#41 ](https://github.com/heiko95/InsertCreator/issues/41)

_Any chance to get the type of "Bibelwort" insert (on the whole screen) for custom inserts?_
New issue created. See: [#42 ](https://github.com/heiko95/InsertCreator/issues/42)
